---
# ======================================================================
# GCPy environment file (based on Python 3.13)
#
# If you wish to build a Mamba/Conda environment with the dependencies
# for GCPy, use this command:
#
# $ mamba env create -n gcpy_env --file=/path/to/gcpy/environment.yml
# =====================================================================
name: gcpy_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy        ==0.24.0     # Geospatial data processing
  - cf_xarray      ==0.10.0     # CF conventions for xarray
  - dask           ==2025.3.0   # Parallel library; backend for xarray
  - esmf           ==8.8.1      # Earth System Model Framework
  - esmpy          ==8.8.1      # Python wrapper for ESMF
  - gridspec       ==0.1.0      # Define Earth System Model grids
  - ipython        ==9.0.0      # Interactive Python (used by Jupyter)
  - joblib         ==1.4.2      # Parallelize python code
  - jupyter        ==1.1.1      # Jupyter Notebook
  - matplotlib     ==3.10.1     # Creates plots and visualizations
  - netcdf4        ==1.7.2      # Python wrapper for netCDF
  - netcdf-fortran ==4.6.1      # Python wrapper for netCDF-Fortran
  - numpy          ==2.1.3      # Optimized mathematical functions
  - pandas         ==2.2.3      # Tables/timeseries manipulation
  - pip            ==25.2       # Install packages from PyPi
  - pylint         ==3.3.4      # Python linter
  - pyproj         ==3.7.1      # Python map projections library
  - python         ==3.13       # Python language
  - pypdf          ==6.6.2      # PDF utilities (bookmarks, etc.)
  - requests       ==2.32.4     # HTTP library
  - scipy          ==1.15.2     # Scientific python package
  - sparselt       ==0.1.3      # Regridding earth system model data
  - tabulate       ==0.9.0      # Pretty-printing for column data
  - tk             ==8.6.13     # Tcl/tk library
  - xarray         ==2025.1.2   # Read data from netCDF etc files
  - xesmf          ==0.8.8      # Universal regridder
