---
# ======================================================================
# ReadTheDocs environment file
#
# If you wish to build a Mamba/Conda environment with the dependencies
# needed for building the ReadTheDocs documentation, use:
#
# $ mamba env create -n rtd_env --file=read_the_docs_environment.yml
# ======================================================================
name: rtd_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.12.0
  - sphinx==7.2.6
  - sphinx_rtd_theme==2.0.0
  - sphinxcontrib-bibtex==2.6.2
  - sphinx-autobuild==2021.3.14
  - recommonmark==0.7.1
  - docutils==0.20.1
  - jinja2==3.1.6


