---
# =====================================================================
# Benchmark configuration file (**EDIT AS NEEDED**)
# customize in the following manner:
#
# (1) Edit the path variables so that they point to folders
#     containing model data
# (2) Edit the version strings for each benchmark simulation
# (3) Edit the switches that turn on/off creating of plots and
#     tables as well as other plotting options
# (4) If necessary, edit labels for the dev and ref versions
#
# Note: When doing GCHP vs GCC comparisions gchp_dev will be compared
# to gcc_dev (not gcc_ref!). This ensures consistency in version names
# when doing GCHP vs GCC diff-of-diffs.
# =====================================================================
#
# Configuration for 1-month FullChemBenchmark
#
# paths:
#   main_dir:    High-level directory containing ref & dev rundirs
#   results_dir: Directory where plots/tables will be created
#   weights_dir: Path to regridding weights
#
paths:
  main_dir: /path/to/benchmark/main/dir
  results_dir: /path/to/BenchmarkResults
  weights_dir: /n/holylfs06/LABS/jacob_lab/Shared/GEOS-CHEM/gcgrid/gcdata/ExtData/GCHP/RegriddingWeights
#
# data: Contains configurations for ref and dev runs
#   version:          Version string (must not contain spaces)
#   dir:              Path to run directory
#   species_metadata: Path to species_database.yml file (in dir)
#   outputs_subdir:   Subdirectory w/ GEOS-Chem diagnostic files
#   restarts_subdir:  Subdirectory w/ GEOS-Chem restarts
#   logs_subdir:      Subdirectory w/ GEOS-Chem log files
#   logs_template:    Template for log file names (may include tokens)
#   bmk_start:        Simulation start date (YYYY-MM-DDThh:mm:ss)
#   bmk_end:          Simulation end date (YYYY-MM-DDThh:mm:ss)
#   resolution:       GCHP resolution string
#
data:
  ref:
    gcc:
      version: GCC_ref
      dir: GCC_ref
      species_metadata: species_database.yml
      outputs_subdir: OutputDir
      restarts_subdir: Restarts
      logs_subdir: .
      logs_template: "GC.log"
      bmk_start: "2019-07-01T00:00:00"
      bmk_end: "2019-08-01T00:00:00"
    gchp:
      version: GCHP_ref
      dir: GCHP_ref
      species_metadata: species_database.yml
      outputs_subdir: OutputDir
      restarts_subdir: Restarts
      logs_subdir: .
      logs_template: "gchp.%Y%m%d_0000z.log"      
      bmk_start: "2019-07-01T00:00:00"
      bmk_end: "2019-08-01T00:00:00"
      is_pre_14.0: False
      resolution: c24
  dev:
    gcc:
      version: GCC_dev 
      dir: GCC_dev
      species_metadata: species_database.yml
      outputs_subdir: OutputDir
      restarts_subdir: Restarts
      logs_subdir: .
      logs_template: "GC.log"      
      bmk_start: "2019-07-01T00:00:00"
      bmk_end: "2019-08-01T00:00:00"
    gchp:
      version: GCHP_dev
      dir: GCHP_dev
      species_metadata: species_database.yml
      outputs_subdir: OutputDir
      restarts_subdir: Restarts
      logs_subdir: Logs
      logs_template: "gchp.%Y%m%d_0000z.log"
      bmk_start: "2019-07-01T00:00:00"
      bmk_end: "2019-08-01T00:00:00"
      is_pre_14.0: False
      resolution: c24
#
# options: Customizes the benchmark plot output
#
options:
  #
  # bmk_type: Specifies the type of benchmark
  #
  bmk_type: FullChemBenchmark
  #
  # comparisons: Specifies the comparisons to perform.
  #
  comparisons:
    gcc_vs_gcc:
      run: True
      dir: GCC_version_comparison
      tables_subdir: Tables
    gchp_vs_gcc:
      run: True
      dir: GCHP_GCC_comparison
      tables_subdir: Tables
    gchp_vs_gchp:
      run: True
      dir: GCHP_version_comparison
      tables_subdir: Tables
    gchp_vs_gcc_diff_of_diffs:
      run: True
      dir: GCHP_GCC_diff_of_diffs
  #
  # outputs: Specifies the plots and tables to generate
  #
  outputs:
    #
    # Benchmark plots
    #
    plot_aod: True
    plot_conc: True
    plot_drydep: True
    plot_emis: True
    plot_jvalues: True
    plot_options:
      by_spc_cat: True
      by_hco_cat: True
    #
    # Benchmark tables
    #
    emis_table: True
    mass_accum_table: False
    mass_table: True
    OH_metrics: True
    ops_budget_table: False
    sanity_check_table: True
    ste_table: True # GCC only
    summary_table: True
    timing_table: True
    #
    # Comparison plots for selected collections
    # (not normally used for benchmarks)
    #
    plot_budget: False
    plot_2d_met: False
    plot_3d_met: False
    plot_uvflux: False
  #
  # n_cores: Specify the number of cores to use.
  # -1: Use $OMP_NUM_THREADS         cores
  # -2: Use $OMP_NUM_THREADS - 1     cores
  # -N: Use $OMP_NUM_THREADS - (N-1) cores
  #  1: Disable parallelization (use a single core)
  #
  n_cores: -1
