---
#
# GitHub action to build the GCPy production environment
# (for Python 3.12) with micromamba
# See: https://github.com/marketplace/actions/setup-micromamba
#
name: build-gcpy-environment-py312

on:
  push:
    branches: [ "main", "dev", "dependabot/*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout the GCPy repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Create "gcpy_env" environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 'latest'
          environment-file: docs/environment_files/gcpy_environment_py312.yml
          init-shell: bash
          cache-environment: false
          generate-run-shell: true
          post-cleanup: 'all'

      - name: Test if "import gcpy" works
        run: python -c "import gcpy"
        shell: micromamba-shell {0}

      - name: Test if we can create a plot
        run: python -m gcpy.examples.plotting.create_test_plot
        shell: micromamba-shell {0}
